#!/bin/sh

mkdir build_x64
cd build_x64
./../configure --enable-static=yes --disable-gprof --disable-binutils --disable-gas --disable-gold --disable-texinfo --disable-gdbserver --target=x86_64-w64-mingw32 --host=x86_64-w64-mingw32

echo "Press enter to continue"
read _

make all LDFLAGS=-static

strip ./gdb/gdb.exe
