#!/bin/sh

EXPAT=""
if [[ -d "./expat/build_x64" ]]; then
 EXPAT="--with-expat --with-libexpat-prefix="$(readlink -m "./expat/build_x64")
fi

mkdir build_x64
cd build_x64
./../configure --enable-static=yes $EXPAT --disable-gprof --disable-binutils --disable-gas --disable-gold --disable-texinfo --disable-gdbserver --disable-ld --target=x86_64-w64-mingw32 --host=x86_64-w64-mingw32

echo "Press enter to continue"
read _

make all LDFLAGS=-static

strip ./gdb/gdb.exe
