#!/bin/sh

echo -n 'procname:'
read procname

find . -name "*.o" -print0 | while read -d $'\0' file
do
 grr=`x86_64-w64-mingw32-nm --print-size "$file" | grep "$procname"`
 if [[ _${grr} != _ ]]; then
  echo $file
  echo $grr
 fi
done

echo "Press enter to continue"
read _
