#!/bin/sh

if [[ ! -f "configure" ]]; then
 ./buildconf.sh
fi

mkdir "./build_x64"

./configure CPPFLAGS=-DXML_LARGE_SIZE --prefix=$(readlink -m "./build_x64") --enable-static=yes --host=x86_64-w64-mingw32

echo "Press enter to continue"
read _

make clean
make install LDFLAGS=-static

